// Contenido del pptx del Módulo 3. Las notas del orador repiten la narración del video.
module.exports = {
  titulo: 'Especificar antes de construir',
  bajada: 'Por qué la spec es el contrato entre vos y el agente, y cómo aprobar el plan antes de tocar código.',
  slides: [
    { tipo: 'portada', chip: '≈ 8 min · challenge al final',
      notas: 'En este módulo aprendemos a decirle al agente qué construir antes de que escriba una línea. Termina con el Paso 2 del recorrido: la spec de la próxima feature. Ejemplo: reembolsos parciales en pagos-api.' },
    { tipo: 'objetivos', items: [
      ['Spec-Driven Development', 'La spec como contrato: todo se mide contra ella.'],
      ['La spec en seis piezas', 'Qué tiene que tener para que el agente no invente.'],
      ['Aprobar el plan', 'Preguntas cerradas y el checkpoint más valioso.'],
      ['El modo Plan de Codex', 'Planificar y preguntar antes de tocar el repo.']],
      notas: 'Cuatro ideas y un paso práctico. Al final, challenge y quiz.' },
    { tipo: 'imagen', section: 'El problema', titulo: 'Los huecos se llenan con supuestos', img: 'problema',
      bullets: ['Juli pide: "Agregá reembolsos parciales"', '¿Se puede reembolsar más que el pago? Asumió: sí', '¿Varios sobre un mismo pago? Asumió: no', '¿Quién puede hacerlos? Asumió: cualquiera'],
      clave: 'Un agente ejecuta lo que le decís, no lo que quisiste decir.',
      notas: 'Codex construye la feature rápido, pero decide solo tres cosas que nadie le dijo. Los huecos los completa con supuestos.' },
    { tipo: 'imagen', section: '3.1 · SDD', titulo: 'Spec-Driven Development', img: 'sdd',
      bullets: ['Antes de generar código, se escribe y valida la spec', 'Spec → plan → código → verificación', 'Todo se verifica contra la spec', 'QA sabe exactamente qué validar'],
      clave: 'La spec es el contrato entre personas y agentes.',
      notas: 'En SDD la spec es el contrato. Las ambigüedades aparecen antes de codear, el plan se puede revisar y aprobar, y QA sabe qué validar.' },
    { tipo: 'imagen', section: '3.1 · SDD', titulo: 'Minutos contra horas', img: 'costo',
      bullets: ['Corregir una spec: minutos', 'Corregir el código de una spec ambigua: horas', 'Especificar no es burocracia'],
      clave: 'Es la forma de que el agente construya lo que realmente necesitás.',
      notas: 'Corregir una spec cuesta minutos. Corregir el código que salió de una spec ambigua cuesta horas.' },
    { tipo: 'imagen', section: '3.2 · Seis piezas', titulo: 'La spec en seis piezas', img: 'spec',
      bullets: ['Qué se construye', 'Actores', 'Flujo principal', 'Casos borde', 'Fuera de scope', 'Criterios de aceptación'], size: 14,
      clave: 'Si alguien nuevo no podría implementarla sin preguntar, el agente tampoco.',
      notas: 'Ejemplo con reembolsos parciales. El puente con análisis funcional: si la historia de usuario ya trae estas seis piezas, el agente arranca con la mitad del trabajo hecho. La spec dice qué y por qué; el cómo va en el plan.' },
    { tipo: 'imagen', section: '3.3 · Aprobar el plan', titulo: 'Ambigüedades → preguntas cerradas', img: 'pregunta',
      bullets: ['Nunca supuestos', 'Se responden en segundos: sí o no, a o b', 'La respuesta vuelve a la spec'],
      clave: 'Así trabaja el Explorador del TSOFT AI Dev Kit.',
      notas: 'Aunque la spec sea buena siempre queda alguna duda. La regla es convertirla en pregunta cerrada, no en supuesto.' },
    { tipo: 'imagen', section: '3.3 · Aprobar el plan', titulo: 'El checkpoint más valioso', img: 'plan',
      bullets: ['El agente propone el plan: archivos, orden y verificación', 'Vos lo aprobás antes de que se escriba código', 'Recién ahí se implementa'],
      clave: 'Aprobar el plan antes de que se escriba una sola línea de código.',
      notas: 'Con la spec clara, el agente propone un plan. Aprobarlo es barato y evita construir rápido sobre un error.' },
    { tipo: 'imagen', section: '3.3 · Aprobar el plan', titulo: 'Tres checkpoints alcanzan', img: 'checkpoints',
      bullets: ['Spec validada', 'Plan aprobado (el más valioso)', 'Diff revisado', 'Muy pocos: se construye sobre un error', 'Demasiados: fatiga de aprobación'], size: 14,
      clave: 'Human in the loop donde importa, no en cada paso.',
      notas: 'Muy pocos checkpoints: el agente construye rápido sobre un error que nadie vio. Demasiados: se termina aprobando sin leer, que es peor que no aprobar.' },
    { tipo: 'imagen', section: '3.4 · Modo Plan', titulo: 'El modo Plan de Codex', img: 'modoplan',
      bullets: ['Se activa con /plan (o Shift+Tab)', 'No edita: lee, junta contexto y pregunta', 'Propone el plan', '"Implement this plan?": aceptar o seguir ajustando'],
      clave: 'Planificar y preguntar antes de tocar el repo.',
      notas: 'Verificado en la documentación oficial de Codex (septiembre 2026): en modo Plan no realiza acciones que modifiquen el repo, hace preguntas para cerrar decisiones y al final pregunta si implementa el plan. La terminal del video es una simulación. Hay un reporte de que Shift+Tab podría no funcionar en la extensión de VS Code: usar /plan.' },
    { tipo: 'imagen', section: '3.4 · Modo Plan', titulo: 'Revisar contra la spec', img: 'review',
      bullets: ['/review revisa tus cambios', 'Sumale la spec como instrucción', 'Pedile a Codex que te entreviste para armar la spec'],
      clave: 'Revisá contra lo que se pidió, no solo contra el código.',
      notas: 'La guía oficial de buenas prácticas de Codex recomienda pedirle que te entreviste para convertir una idea vaga en una especificación antes de codear.' },
    { tipo: 'pasos', section: '3.5 · Paso 2', titulo: 'Paso 2 · La spec de tu próxima feature', chip: '45 minutos · en tu repo',
      pasos: [['Escribila', 'Seis piezas en docs/<feature>.md, o que Codex te entreviste.'],
              ['Pasala por /plan', 'Que te pregunte lo que no esté claro. Actualizá la spec.'],
              ['Aprobá y revisá', 'Aprobá el plan cuando lo entiendas. Al final, /review contra la spec.']],
      clave: 'En el Módulo 4, el agente se verifica solo contra esos criterios.',
      notas: 'En el TSOFT AI Dev Kit este flujo lo hacen el Explorador (scope y preguntas cerradas) y el Planificador (design.md), con la aprobación del plan antes del Desarrollador. Lo vemos en el Módulo 6.' },
    { tipo: 'resumen', items: [
      'Un agente ejecuta lo que le decís, no lo que quisiste decir.',
      'La spec es el contrato: todo se verifica contra ella.',
      'Seis piezas: qué, actores, flujo, borde, fuera de scope, criterios.',
      'Ambigüedades → preguntas cerradas. Nunca supuestos.',
      'Aprobar el plan antes de escribir código.'] },
    { tipo: 'challenge' },
    { tipo: 'cierre', siguiente: 'Módulo 4 · Que se verifique solo' }
  ]
};
