// Contenido del pptx del Módulo 1. Las notas del orador repiten la narración del video.
module.exports = {
  titulo: 'Del chat al agente',
  bajada: 'Qué cambia cuando la IA deja de hablar y empieza a hacer.',
  slides: [
    { tipo: 'portada', chip: '≈ 8 min · challenge al final',
      notas: 'En el Módulo 0 vimos cómo piensa la IA. En este módulo pasamos de la IA que conversa a la IA que trabaja dentro del proyecto: el agente. Seguimos con pagos-api, el proyecto de Juli.' },
    { tipo: 'objetivos', items: [
      ['El loop agéntico', 'Razonar, actuar, observar: quién hace el trabajo ahora.'],
      ['Tool use', 'Cómo el modelo pasa de hablar a hacer.'],
      ['El harness', 'Qué agrega Codex alrededor del modelo: herramientas, contexto y permisos.'],
      ['Qué modelo para qué tarea', 'Dónde poner el modelo más capaz y dónde no hace falta.']],
      notas: 'Cuatro ideas. Al final hay un challenge y un ejercicio para hacer la primera tarea con Codex en el repo propio.' },
    { tipo: 'imagen', section: 'El problema', titulo: 'En un chat, el loop sos vos', img: 'problema',
      bullets: ['Pedís un fragmento de código', 'Lo copiás, lo pegás y lo probás', 'Volvés con el error… y otra vez', 'La IA escribe; vos hacés todo lo demás'],
      clave: 'Un agente cambia eso: el loop lo hace él.',
      notas: 'En un chat, vos sos el loop: pedís, copiás, probás y volvés con el error. Un agente cambia eso: el loop lo hace él.' },
    { tipo: 'imagen', section: '1.1 · El loop agéntico', titulo: 'El loop agéntico', img: 'loop',
      bullets: ['Razonar: decide qué hacer', 'Actuar: usa una herramienta (leer, editar, ejecutar)', 'Observar: mira el resultado', 'Repite hasta terminar… o hasta trabarse'],
      clave: 'Tu rol: definir el objetivo, los límites y cómo se verifica.',
      notas: 'Ejemplo: Bit valida que el monto del reembolso sea mayor a cero. Lee el código, detecta el problema, edita, corre los tests, ve que uno falla y lo corrige. Nadie copió ni pegó nada. El loop sigue hasta terminar o hasta que necesita ayuda.' },
    { tipo: 'imagen', section: '1.2 · Tool use', titulo: 'Tool use: de hablar a hacer', img: 'tooluse',
      bullets: ['El modelo solo genera texto', 'Con tool use, pide usar una herramienta', 'El harness la ejecuta en tu máquina y le devuelve el resultado', 'Si la acción necesita permiso, el harness te pregunta antes'],
      clave: 'El modelo solo pide. El harness ejecuta, controla y devuelve.',
      notas: 'Un modelo por sí solo no puede leer archivos ni correr nada. Con tool use pide una acción, por ejemplo leer un archivo o correr npm test. El harness, en este caso Codex, la ejecuta y le devuelve el resultado. Si necesita permiso, como salir a internet para instalar algo, te pregunta antes.' },
    { tipo: 'imagen', section: '1.3 · El harness', titulo: 'Modelo + harness = agente', img: 'harness',
      bullets: ['Herramientas: leer, editar, buscar, ejecutar', 'Contexto: qué entra, qué se resume, qué se descarta', 'Permisos y sandbox: qué puede hacer sin preguntarte', 'Extensiones: AGENTS.md, skills, MCP, hooks, subagentes'],
      clave: 'Mismo modelo, distinto harness, distintos resultados.',
      notas: 'Codex y Claude Code son harnesses. Ponen las herramientas, deciden qué contexto le llega al modelo y controlan los permisos. Las extensiones las vemos en los próximos módulos.' },
    { tipo: 'imagen', section: '1.3 · El harness', titulo: 'Permisos en Codex', img: 'permisos',
      bullets: ['read-only: lee y analiza, no modifica', 'workspace-write: edita dentro del proyecto', 'danger-full-access: solo en entornos aislados', 'En un repo git arranca en Auto: edita en el proyecto y pregunta antes de salir', 'Se cambian con /permissions'], size: 14,
      clave: 'Mínimo permiso necesario para la tarea.',
      notas: 'Tres niveles de sandbox. Dentro de un repo git, Codex arranca en el modo Auto: escritura en el proyecto y te pide aprobación si necesita salir de ahí, por ejemplo acceso a la red. Datos verificados en la documentación oficial de Codex en septiembre de 2026.' },
    { tipo: 'imagen', section: '1.4 · Qué modelo', titulo: 'Qué modelo para qué tarea', img: 'modelos',
      bullets: ['Spec ambigua o plan: modelo grande, esfuerzo alto', 'Implementar un plan aprobado: grande, esfuerzo medio', 'Resumir o documentar: chico, esfuerzo bajo', 'En Codex: /model elige modelo y esfuerzo'],
      clave: 'El modelo más capaz, donde el error es más caro.',
      notas: 'Un error al entender la spec se arrastra y crece en el plan, el código y los tests. No nombramos modelos concretos porque cambian seguido: con /model elegís el modelo y el esfuerzo de razonamiento.' },
    { tipo: 'imagen', section: '1.5 · Ejemplo en Codex', titulo: 'La primera tarea de Juli', img: 'codex',
      bullets: ['Objetivo: validar que el monto sea mayor a 0', 'Criterio: que pasen los tests', 'Codex lee, planifica, edita y corre los tests', 'Juli revisa los cambios con /diff'],
      clave: 'Objetivo claro, criterio de verificación y revisar siempre el diff.',
      notas: 'La terminal del video es una simulación. Codex lee los archivos, arma un plan, edita y corre los tests. Con los permisos en Auto trabaja dentro del proyecto. Antes de aceptar, Juli revisa con /diff.' },
    { tipo: 'pasos', section: '1.6 · Probalo vos', titulo: 'Probalo vos', chip: '20 minutos · en tu repo',
      pasos: [['Explorá', 'Abrí Codex en tu repo y pedile que te explique la estructura, sin editar.'],
              ['Una tarea chica', 'Algo acotado, con criterio de verificación: "corré los tests".'],
              ['Revisá el diff', 'Mirá los cambios con /diff antes de aceptar.']],
      clave: 'Arrancá con el repo limpio (git status) para poder volver atrás.',
      notas: 'La primera tarea con Codex en el repo propio. En el Módulo 2 vemos por qué Codex a veces no sabe cómo trabaja tu equipo, y cómo se resuelve con AGENTS.md.' },
    { tipo: 'resumen', items: [
      'En un agente, el loop razonar → actuar → observar lo hace él.',
      'Con tool use, el modelo pide acciones y el harness las ejecuta.',
      'Modelo + harness = agente: herramientas, contexto, permisos, extensiones.',
      'El modelo más capaz, donde el error es más caro.',
      'Tu rol: objetivo, límites y verificación. Siempre revisar el diff.'] },
    { tipo: 'challenge' },
    { tipo: 'cierre', siguiente: 'Módulo 2 · Darle contexto' }
  ]
};
