// Contenido del pptx del Módulo 5. Las notas del orador repiten la narración del video.
module.exports = {
  titulo: 'Capturar y conectar',
  bajada: 'Cómo convertir lo que sabe el equipo en skills y conectar el agente con tus sistemas.',
  slides: [
    { tipo: 'portada', chip: '≈ 9 min · challenge al final',
      notas: 'En este módulo el agente deja de depender de lo que le explicás cada vez, y se conecta con tus sistemas. Termina con el Paso 4: una convención del equipo convertida en skill.' },
    { tipo: 'objetivos', items: [
      ['Skills', 'Lo que sabe el equipo, aplicado siempre igual.'],
      ['¿AGENTS.md, skill o hook?', 'Dónde va cada conocimiento.'],
      ['MCP', 'Conectar el agente con Jira, la base o la API.'],
      ['Prompt injection', 'Por qué todo lo que lee puede ser una orden.']],
      notas: 'Cuatro ideas y un paso práctico. Al final, challenge y quiz.' },
    { tipo: 'imagen', section: 'El problema', titulo: 'Otra vez lo mismo', img: 'problema',
      bullets: ['Juli explica por tercera vez cómo se crea un endpoint', 'Cada persona del equipo lo explica distinto', 'El ticket de Jira se copia y pega a mano'],
      clave: 'El conocimiento vive en cabezas y el agente está desconectado.',
      notas: 'Dos problemas: el conocimiento del equipo no está capturado en ningún lado, y el agente no tiene acceso a los sistemas donde vive la información.' },
    { tipo: 'imagen', section: '5.1 · Skills', titulo: 'Qué es una skill', img: 'skill',
      bullets: ['Una carpeta en .agents/skills, dentro del repo', 'SKILL.md: name, description e instrucciones', 'Opcional: scripts/ y references/', 'La description dice cuándo sí y cuándo no'], size: 14,
      clave: 'Una skill empaqueta cómo se hace un tipo de tarea en tu equipo.',
      notas: 'Según la documentación oficial de Codex (septiembre 2026), las skills del repo viven en .agents/skills; también hay skills de usuario en $HOME/.agents/skills. El SKILL.md del video es un ejemplo.' },
    { tipo: 'imagen', section: '5.1 · Skills', titulo: 'Cómo la elige Codex', img: 'disclosure',
      bullets: ['Al arrancar ve solo nombre y description', 'Carga el SKILL.md completo al usarla', 'Explícita: $nuevo-endpoint', 'Implícita: la tarea coincide con la description'],
      clave: 'Si la description no dice cuándo usarla, no la va a elegir.',
      notas: 'Progressive disclosure: Codex empieza con el nombre y la descripción de cada skill y carga las instrucciones completas cuando decide usarla. Así podés tener muchas skills sin llenar el contexto.' },
    { tipo: 'imagen', section: '5.2 · ¿Dónde va?', titulo: '¿AGENTS.md, skill o hook?', img: 'donde',
      bullets: ['Aplica siempre → AGENTS.md', 'Aplica a un tipo de tarea → skill', 'No puede fallar nunca → hook o regla'],
      clave: 'El AGENTS.md queda corto y cada conocimiento vive donde corresponde.',
      notas: 'Ejemplos: los comandos de test y build van en el AGENTS.md; cómo crear un endpoint, en una skill; bloquear un push a main, en un hook o una regla de comandos (Módulo 4).' },
    { tipo: 'imagen', section: '5.3 · Skills de terceros', titulo: 'Popular no es lo mismo que segura', img: 'terceros',
      bullets: ['Ejemplo real: HyperFrames (HeyGen, Apache-2.0)', 'Marketplace de terceros: npx skills add', 'Camino oficial de Codex: $skill-installer', 'Trae instrucciones que obedece y scripts que ejecuta'], size: 14,
      clave: 'Antes de instalar: leé SKILL.md y scripts, revisá servicios externos, probala aislada.',
      notas: 'HyperFrames es una skill open source para crear videos con HTML. Una de sus partes usa APIs externas de modelos: con código o datos de un cliente, eso tiene que estar aprobado. npx skills add es del marketplace skills.sh, no de la documentación de Codex.' },
    { tipo: 'imagen', section: '5.4 · MCP', titulo: 'Skill contra MCP', img: 'mcp',
      bullets: ['Skill: saber cómo hacerlo', 'MCP: poder hacerlo en otro sistema', 'Jira, base de datos, API, navegador'],
      clave: 'MCP es un estándar para conectar el agente con otros sistemas.',
      notas: 'Con un MCP de Jira, Codex lee el ticket directamente en lugar de que Juli lo copie y pegue.' },
    { tipo: 'imagen', section: '5.4 · MCP', titulo: 'MCP en Codex', img: 'mcpconfig',
      bullets: ['codex mcp add <nombre> -- <comando>', 'O [mcp_servers.<nombre>] en config.toml', 'enabled_tools: solo lo necesario', 'default_tools_approval_mode = "writes"', '/mcp: servidores activos'], size: 14,
      clave: 'El token, en una variable de entorno. Nunca escrito en el archivo.',
      notas: 'Verificado en la documentación oficial de Codex (septiembre 2026). El ejemplo de codex mcp add con context7 es el de la doc; la sección de Jira es ilustrativa. El modo writes pide aprobación antes de usar herramientas que no son de solo lectura.' },
    { tipo: 'imagen', section: '5.5 · Prompt injection', titulo: 'Prompt injection', img: 'injection',
      bullets: ['Texto escondido en un ticket con órdenes', 'El agente no distingue bien instrucción de dato', 'Tickets, web, issues, documentos, respuestas de MCP'],
      clave: 'Todo contenido externo es, potencialmente, una orden.',
      notas: 'El ejemplo del video es un ticket con texto del mismo color que el fondo que pide mandar el .env a una URL externa.' },
    { tipo: 'imagen', section: '5.5 · Prompt injection', titulo: 'Las defensas', img: 'defensas',
      bullets: ['Mínimo privilegio', 'Nunca secretos a su alcance', 'Humano en lo irreversible', 'Red apagada por defecto'],
      clave: 'Documentación de Codex: "Treat web results as untrusted."',
      notas: 'Con datos de clientes, estas defensas no son opcionales. La red viene apagada por defecto en Codex; activarla o sumar búsqueda web aumenta la exposición a prompt injection.' },
    { tipo: 'pasos', section: '5.6 · Paso 4', titulo: 'Paso 4 · Capturar y conectar', chip: '45 minutos · en tu repo',
      pasos: [['Convención', 'Algo que explicás seguido: un endpoint, una migración, un test.'],
              ['Skill', '.agents/skills con su SKILL.md y una buena description.'],
              ['Probala', 'Pedí esa tarea sin nombrar la skill: ¿Codex la elige sola?']],
      clave: 'Opcional: un MCP de solo lectura. Módulo 6: delegar y operar.',
      notas: 'El paso práctico del módulo: capturar una convención del equipo en una skill y comprobar que Codex la elige por su descripción.' },
    { tipo: 'resumen', items: [
      'Skill: SKILL.md en .agents/skills; la description decide.',
      'Siempre → AGENTS.md · tipo de tarea → skill · nunca falla → hook.',
      'Skills de terceros: se revisan como cualquier dependencia.',
      'MCP: conecta el agente con tus sistemas, con mínimo privilegio.',
      'Prompt injection: todo contenido externo puede ser una orden.'] },
    { tipo: 'challenge' },
    { tipo: 'cierre', siguiente: 'Módulo 6 · Delegar y operar' }
  ]
};
