// Contenido del pptx del Módulo 4. Las notas del orador repiten la narración del video.
module.exports = {
  titulo: 'Que se verifique solo',
  bajada: 'Cómo pasar de "confío en el modelo" a "está garantizado": verificación, hooks y revisión.',
  slides: [
    { tipo: 'portada', chip: '≈ 8 min · challenge al final',
      notas: 'En este módulo el agente aprende a saber si lo hizo bien antes de que el error nos llegue. Termina con el Paso 3: que el agente pueda correr tests y build en el repo propio.' },
    { tipo: 'objetivos', items: [
      ['Feedback loop', 'Que el agente se verifique y se corrija solo.'],
      ['Hooks', 'Garantías que no dependen de que el modelo se acuerde.'],
      ['Reglas de comandos', 'Qué puede ejecutar, qué necesita aprobación y qué nunca.'],
      ['Revisión en tres filtros', 'El agente no se aprueba a sí mismo.']],
      notas: 'Cuatro ideas y un paso práctico. Al final, challenge y quiz.' },
    { tipo: 'imagen', section: 'El problema', titulo: '"Listo, todo funciona"', img: 'problema',
      bullets: ['Codex terminó los reembolsos parciales y dijo "listo"', 'Juli lo mergeó', 'QA encontró un reembolso negativo que pasaba', 'Nadie había corrido los tests'],
      clave: 'Un agente que no puede verificarse te entrega el error a vos.',
      notas: 'El tono seguro no es evidencia. Sin forma de verificar, el error llega hasta QA o hasta producción.' },
    { tipo: 'imagen', section: '4.1 · Feedback loop', titulo: 'Feedback loop', img: 'loop',
      bullets: ['Escribe el código', 'Corre tests, lint y build', 'Lee el error y corrige', 'Recién dice "listo" con evidencia'],
      clave: 'Lo más valioso: una forma de saber si lo hizo bien.',
      notas: 'Un test falla, Codex lee el mensaje, entiende qué falta y lo arregla, sin intervención. La terminal del video es una simulación.' },
    { tipo: 'imagen', section: '4.1 · Feedback loop', titulo: 'Qué necesita para verificarse', img: 'necesita',
      bullets: ['Comandos de test, lint y build en el AGENTS.md', 'Tests existentes, aunque sean pocos', 'Tipado estricto y linter', 'Pedírselo explícito: "mostrame el resultado"'],
      clave: 'La guía oficial de Codex: que cree tests, corra los chequeos y confirme el resultado.',
      notas: 'La guía de buenas prácticas de Codex recomienda incluir los comandos de build, test y lint en el AGENTS.md y pedirle que cree tests cuando falten, corra los chequeos relevantes y confirme el resultado.' },
    { tipo: 'imagen', section: '4.2 · Hooks', titulo: 'Sugerencia contra garantía', img: 'garantia',
      bullets: ['En el AGENTS.md: se cumple casi siempre', 'Como hook: se cumple siempre', 'Lo que no puede fallar nunca, en un hook'],
      clave: 'Regla de oro (Módulo 0): lo que tiene que pasar siempre, hacelo determinístico.',
      notas: 'Una instrucción es una sugerencia; un hook ejecuta la acción automáticamente cuando ocurre el evento, sin depender de que el modelo se acuerde.' },
    { tipo: 'imagen', section: '4.3 · Hooks en Codex', titulo: 'Hooks en Codex', img: 'hooks',
      bullets: ['Se activan con hooks = true en config.toml', 'Se definen en .codex/hooks.json (global o del repo)', 'Eventos: PreToolUse, PostToolUse, Stop, SessionStart…', 'Un hook puede bloquear una acción'], size: 14,
      clave: 'Ejemplo: un push directo a main, bloqueado antes de ejecutarse.',
      notas: 'Verificado en la documentación oficial de Codex (septiembre 2026). Un hook ejecuta un comando propio; para bloquear, el script sale con código 2 o devuelve una decisión deny. El archivo del video es un ejemplo.' },
    { tipo: 'imagen', section: '4.3 · Hooks en Codex', titulo: 'Usos típicos', img: 'hooks2',
      bullets: ['Antes de un comando: bloquear lo riesgoso', 'Después de editar: correr el formateador', 'Al terminar: lint y tests, y reportar'],
      clave: 'Codex te pide revisar y aprobar cada hook antes de que corra.',
      notas: 'Los hooks se revisan y aprueban antes de ejecutarse, y otra vez si cambian.' },
    { tipo: 'imagen', section: '4.4 · Reglas', titulo: 'Reglas de comandos', img: 'reglas',
      bullets: ['Archivos .rules en .codex/rules/', 'allow: se ejecuta', 'prompt: pide aprobación', 'forbidden: nunca', 'Gana la más restrictiva'], size: 14,
      clave: 'Experimentales: pueden cambiar. Probalas con codex execpolicy check.',
      notas: 'Las reglas definen un prefijo de comando y una decisión. La documentación oficial las marca como experimentales.' },
    { tipo: 'imagen', section: '4.5 · Tres filtros', titulo: 'Revisión en tres filtros', img: 'filtros',
      bullets: ['1. Auto-verificación: tests, lint y build', '2. Revisor separado: /review o @codex review en el PR', '3. Revisión humana del diff, siempre'],
      clave: 'Quien escribió el código no es el mejor revisor. Tampoco cuando es un agente.',
      notas: '/review revisa el working tree enfocándose en cambios de comportamiento y tests faltantes. En GitHub, comentar @codex review en el PR pide una revisión; sigue las reglas de la sección Code Review Rules del AGENTS.md.' },
    { tipo: 'pasos', section: '4.6 · Paso 3', titulo: 'Paso 3 · Que se verifique solo', chip: '45 minutos · en tu repo',
      pasos: [['Comandos', 'Test, lint y build al AGENTS.md. Si no hay tests, que Codex cree algunos.'],
              ['Evidencia', '"Corré los chequeos y mostrame el resultado" antes de decir listo.'],
              ['Una garantía', 'La regla que nunca se rompe, como hook o regla de comandos.']],
      clave: 'Módulo 5: skills y conexión con tus sistemas.',
      notas: 'El paso práctico del módulo: que el agente pueda verificarse en el repo propio y que al menos una regla crítica sea una garantía.' },
    { tipo: 'resumen', items: [
      'Lo más valioso: una forma de saber si lo hizo bien.',
      'Feedback loop: escribe, verifica, lee el error y corrige.',
      'Lo que nunca puede fallar: hook o regla, no prompt.',
      'Hooks y reglas de Codex: bloquean, preguntan o ejecutan solos.',
      'Tres filtros antes del merge.'] },
    { tipo: 'challenge' },
    { tipo: 'cierre', siguiente: 'Módulo 5 · Capturar y conectar' }
  ]
};
