// Contenido del pptx del Módulo 6 (último del curso). Las notas del orador repiten la narración del video.
module.exports = {
  titulo: 'Delegar y operar',
  bajada: 'Subagentes, CI, costos y el TSOFT AI Dev Kit: delegar sin perder el control.',
  slides: [
    { tipo: 'portada', chip: '≈ 10 min · challenge al final',
      notas: 'Último módulo: cómo pasar de un agente que te ayuda a un equipo de agentes que trabaja con vos. Termina con el Paso 5: el kit completo en una feature real.' },
    { tipo: 'objetivos', items: [
      ['Subagentes', 'Delegar partes del trabajo, cada una con su contexto.'],
      ['Delegar con control', 'Mínimo privilegio y un humano entre paso y paso.'],
      ['Operar', 'CI, trazabilidad, costos, evals y plugins.'],
      ['El TSOFT AI Dev Kit', 'Todo el curso, junto, listo para usar.']],
      notas: 'Cuatro ideas, un ejercicio de "¿qué está mal?" y un paso práctico. Al final, challenge y quiz.' },
    { tipo: 'imagen', section: 'El problema', titulo: 'Una sola sesión para todo', img: 'problema',
      bullets: ['Explorar, planificar, implementar, documentar y testear en la misma sesión', 'El contexto se llena y se pierde el foco', 'No queda claro qué se aprobó'],
      clave: 'Un solo agente haciendo todo no escala: hay que delegar sin perder el control.',
      notas: 'La sesión se olvida de decisiones del plan, mezcla documentación con código y no deja claro qué aprobó Juli.' },
    { tipo: 'imagen', section: '6.1 · Subagentes', titulo: 'Qué es un subagente', img: 'subagentes',
      bullets: ['La sesión principal le delega una parte', 'Trabaja en su propio hilo', 'Con sus instrucciones y sus permisos', 'Devuelve el resultado'],
      clave: 'La sesión principal no se llena de detalles.',
      notas: 'En Codex, los subagentes corren en su propio agent thread y pueden correr en paralelo.' },
    { tipo: 'imagen', section: '6.1 · Subagentes', titulo: 'Subagentes en Codex', img: 'toml',
      bullets: ['Un TOML por agente en .codex/agents/', 'Obligatorio: name, description, developer_instructions', 'Opcional: modelo, esfuerzo, sandbox_mode', 'Se piden en lenguaje natural o desde AGENTS.md o una skill'], size: 14,
      clave: 'No puede preguntarte en vivo: deja preguntas cerradas y la sesión principal te las hace.',
      notas: 'Verificado en la documentación oficial de Codex (septiembre 2026). Si el agente no define sandbox_mode, hereda el de la sesión. Con /agents los seguís en la terminal.' },
    { tipo: 'imagen', section: '6.2 · Delegar con control', titulo: 'Delegar con control', img: 'control',
      bullets: ['Explorar y planificar: read-only', 'Implementar, documentar y testear: workspace-write', 'Acceso total: ninguno', 'Entre paso y paso, tu aprobación'],
      clave: 'Nadie toca código sin un plan aprobado.',
      notas: 'Mínimo privilegio y Human in the Loop. El sandbox y las aprobaciones se ajustan por agente; lo irreversible siempre pasa por un humano.' },
    { tipo: 'imagen', section: '6.3 · Operar', titulo: 'CI y trazabilidad', img: 'ci',
      bullets: ['codex exec: sin interacción, para scripts y CI', 'Por defecto: solo lectura', 'Action oficial: openai/codex-action, con la clave como secret', '--json y codex resume: cada paso queda registrado'], size: 14,
      clave: 'En el kit, cada feature deja su rastro en tsoft-dev/.',
      notas: '--full-auto quedó deprecado: para escribir se usa --sandbox workspace-write. Codex guarda las sesiones de forma local; con --json el evento turn.completed trae el uso de tokens.' },
    { tipo: 'imagen', section: '6.3 · Operar', titulo: 'Costos', img: 'costos',
      bullets: ['Modelo y esfuerzo según la tarea', 'AGENTS.md corto y pocos servidores MCP', 'Prompts y material acotados', '/status para ver el uso · /compact'],
      clave: 'Explorar no necesita lo mismo que diseñar.',
      notas: 'Consejos de la página de precios de la documentación de Codex. Las barras de esfuerzo del video son un ejemplo.' },
    { tipo: 'imagen', section: '6.3 · Operar', titulo: 'Evals', img: 'evals',
      bullets: ['Casos con resultado esperado', '10 a 20 pedidos, con casos que NO deben activar la skill', 'Se corren con codex exec --json', 'Cada falla, un caso más'],
      clave: 'Como los tests, pero para el agente.',
      notas: 'Fuente: artículo "eval skills" del blog oficial de OpenAI Developers. No figura en la documentación de producto de Codex.' },
    { tipo: 'imagen', section: '6.4 · Plugins', titulo: 'Plugins', img: 'plugins',
      bullets: ['Empaquetan skills, servidores MCP y hooks', 'Manifiesto: plugin.json', '/plugins para instalar y activar', 'Marketplace del equipo en .agents/plugins/'],
      clave: 'Un plugin de terceros se revisa antes de instalarlo.',
      notas: 'Los plugins sirven para distribuir lo que funciona en el equipo. Misma regla que las skills de terceros del Módulo 5.' },
    { tipo: 'imagen', section: '6.5 · El TSOFT AI Dev Kit', titulo: 'El TSOFT AI Dev Kit', img: 'kit',
      bullets: ['$orquestador coordina 5 subagentes', 'docs/ → tsoft-dev/<feature>/', 'Después de cada paso: ¿aprobás? ¿seguimos?', 'max_depth = 1: no se invocan entre sí'], size: 14,
      clave: 'El desarrollador nunca toca código sin plan aprobado.',
      notas: 'Explorador y planificador en solo lectura; desarrollador, documentador y QA con escritura en el workspace. Si pausás, el estado queda en orquestador-estado.md para retomar.' },
    { tipo: 'imagen', section: '6.5 · El TSOFT AI Dev Kit', titulo: 'Los archivos del kit son tuyos', img: 'exclude',
      bullets: ['.codex/, AGENTS.md y tsoft-dev/ en .git/info/exclude', 'Sin tocar el .gitignore del cliente', 'docs/ no se excluye: es del equipo'],
      clave: 'Exclusión local, no en el repo del cliente.',
      notas: 'Así el kit no ensucia el repositorio del cliente, y las specs en docs/ se comparten por git.' },
    { tipo: 'imagen', section: '6.6 · ¿Qué está mal?', titulo: '¿Qué está mal?', img: 'mal',
      bullets: ['1. danger-full-access → workspace-write', '2. approval_policy = "never" → on-request', '3. Token en el AGENTS.md → variable de entorno o gestor de secretos'],
      clave: 'Mínimo privilegio · humano en el loop · nunca secretos al alcance.',
      notas: 'Ejercicio: mostrar primero la configuración sin las respuestas y dejar que el grupo encuentre los tres errores.' },
    { tipo: 'pasos', section: '6.7 · Paso 5', titulo: 'Paso 5 · El kit en una feature real', chip: '1 feature · en tu repo',
      pasos: [['Instalá el kit', 'En tu repo, con sus archivos en .git/info/exclude.'],
              ['Una feature real', 'Material en docs/ y $orquestador <feature>.'],
              ['Todo el flujo', 'Aprobá cada paso y anotá qué ajustarías.']],
      clave: 'Compartí lo aprendido en el canal del AI Adoption Program.',
      notas: 'El último paso del recorrido: usar el kit completo, de punta a punta, en una feature chica y real.' },
    { tipo: 'resumen', items: [
      'Subagentes: cada parte, con su contexto y sus permisos.',
      'Mínimo privilegio y un humano entre paso y paso.',
      'codex exec y la Action oficial llevan Codex a CI, con trazas.',
      'Modelo y esfuerzo según la tarea; evals para no retroceder.',
      'El TSOFT AI Dev Kit: todo el curso, junto.'] },
    { tipo: 'challenge' },
    { tipo: 'cierre', siguiente: 'Tu próxima feature, con el TSOFT AI Dev Kit' }
  ]
};
