// Contenido del pptx del Módulo 2. Las notas del orador repiten la narración del video.
module.exports = {
  titulo: 'Darle contexto',
  bajada: 'Por qué el agente no sabe cómo trabaja tu equipo, y cómo se lo enseñás una sola vez.',
  slides: [
    { tipo: 'portada', chip: '≈ 8 min · challenge al final',
      notas: 'En este módulo aprendemos a darle al agente la información que necesita para trabajar como el equipo. Termina con el Paso 1 del recorrido: el AGENTS.md del proyecto propio.' },
    { tipo: 'objetivos', items: [
      ['Context engineering', 'Qué información tiene el agente, cuándo y cuánta.'],
      ['AGENTS.md', 'La memoria del proyecto: qué va, qué no y dónde lo lee Codex.'],
      ['Progressive disclosure', 'Cómo tener mucho conocimiento sin llenar la ventana.'],
      ['Tu AGENTS.md en Codex', 'Crearlo con /init, mejorarlo y probar que funciona.']],
      notas: 'Cuatro ideas y un paso práctico. Al final, challenge y quiz.' },
    { tipo: 'imagen', section: 'El problema', titulo: 'La misma corrección, todos los días', img: 'problema',
      bullets: ['Codex vuelve a usar console.log', 'El equipo siempre usa logger.error', 'Juli lo corrige… otra vez', 'No es el modelo: le falta información'],
      clave: 'Ante un mal resultado: ¿el agente tenía la información para hacerlo bien?',
      notas: 'Juli ya trabaja con Codex en pagos-api, pero todos los días corrige lo mismo: console.log en lugar de logger.error. No es un problema del modelo: el agente no tiene esa información.' },
    { tipo: 'imagen', section: '2.1 · Context engineering', titulo: 'Context engineering', img: 'contexto',
      bullets: ['Prompt engineering: cómo pedís', 'Context engineering: qué sabe el agente mientras trabaja', 'Con agentes, lo segundo pesa mucho más'],
      clave: 'La mayoría de los malos resultados son falta de contexto, no de modelo.',
      notas: 'El prompt engineering se ocupa de cómo pedir; el context engineering, de qué información tiene el agente mientras trabaja. Con agentes, lo segundo pesa mucho más.' },
    { tipo: 'imagen', section: '2.1 · Context engineering', titulo: 'Qué, cuándo y cuánto', img: 'qcc',
      bullets: ['Qué: convenciones, arquitectura, la spec, ejemplos reales', 'Cuándo: lo general siempre; lo específico, solo si la tarea lo pide', 'Cuánto: poco da resultados genéricos; demasiado, lento y caro'],
      clave: 'El objetivo es el punto justo de contexto.',
      notas: 'Tres preguntas para diseñar el contexto. Con poco, el resultado es genérico; con demasiado, el agente se pierde, tarda y cuesta más.' },
    { tipo: 'imagen', section: '2.2 · AGENTS.md', titulo: 'AGENTS.md: la memoria del proyecto', img: 'agentsmd',
      bullets: ['Un archivo en el repo que Codex lee siempre', 'Stack, estructura, comandos de build y test', 'Convenciones concretas y lo que nunca se hace', 'Específico: "logger.error, nunca console.log"'], size: 14,
      clave: 'Si lo corregís dos veces, va al AGENTS.md.',
      notas: 'AGENTS.md es un archivo en el repo que Codex lee antes de cualquier tarea. Ahí va lo que aplica siempre. La clave es ser específico: "usamos buenas prácticas" no le dice nada.' },
    { tipo: 'imagen', section: '2.2 · AGENTS.md', titulo: 'Dónde lo lee Codex', img: 'jerarquia',
      bullets: ['Global: ~/.codex/AGENTS.md (tus preferencias)', 'Raíz del repo: el proyecto', 'Subcarpeta: reglas de esa parte', 'Se suman en orden; el más cercano manda', 'Límite combinado: 32 KiB'], size: 14,
      clave: 'Corto y general. Nunca tokens, contraseñas ni datos de producción.',
      notas: 'Codex arma el contexto sumando el AGENTS.md global, el de la raíz del repo y el de la carpeta donde trabajás. El más cercano va último y manda. Entre todos no pueden pasar de 32 KiB. Existe también AGENTS.override.md para pisar reglas de un nivel. Verificado en la documentación oficial de Codex, septiembre 2026.' },
    { tipo: 'imagen', section: '2.3 · Progressive disclosure', titulo: 'Progressive disclosure', img: 'disclosure',
      bullets: ['Nivel 1: AGENTS.md, siempre cargado', 'Nivel 2: nombre y descripción de cada guía, en una línea', 'Nivel 3: la guía completa, solo cuando hace falta', 'Así funcionan las skills de Codex'],
      clave: 'Decenas de guías sin llenar la ventana. Las skills, en el Módulo 5.',
      notas: 'Documentación oficial: Codex arranca con el nombre y la descripción de cada skill, y carga el SKILL.md completo cuando decide usarla. La lista inicial de skills usa como máximo el 2% de la ventana de contexto.' },
    { tipo: 'imagen', section: '2.4 · En Codex', titulo: 'Crear tu AGENTS.md con /init', img: 'init',
      bullets: ['/init crea un AGENTS.md para el repo', 'Si ya existe uno, no lo pisa', 'Es un borrador: revisalo y hacelo específico', 'Sumá las correcciones que más repetís'],
      clave: 'El borrador lo hace Codex; lo específico lo ponés vos.',
      notas: 'La terminal del video es una simulación. /init crea el AGENTS.md; si ya existe, avisa y no hace nada. Después hay que revisarlo y sumar comandos reales, convenciones concretas y lo que nunca se hace.' },
    { tipo: 'imagen', section: '2.4 · En Codex', titulo: 'La prueba: sesión nueva', img: 'prueba',
      bullets: ['Mismo pedido de siempre', 'Codex lee el AGENTS.md', 'Usa logger.error sin que nadie lo corrija', '/status y /compact para cuidar el contexto'],
      clave: 'Lo importante, escrito en el AGENTS.md: dicho una vez en el chat, se puede perder.',
      notas: '/status muestra la configuración y el uso de tokens; /compact resume la conversación. Codex también compacta solo cuando la ventana se llena, y ahí se pueden perder detalles dichos en el chat.' },
    { tipo: 'pasos', section: '2.5 · Paso 1', titulo: 'Paso 1 · Tu AGENTS.md', chip: '30 minutos · en tu repo',
      pasos: [['Crealo', 'Con /init o pidiéndole a Codex que analice el repo.'],
              ['Hacelo tuyo', 'Corto y específico: comandos, convenciones, lo que nunca.'],
              ['Probalo', 'Sesión nueva, un pedido de siempre: ¿lo aplica solo?']],
      clave: 'Repo de un cliente: excluilo con .git/info/exclude.',
      notas: 'En repos de clientes, los archivos del kit de TSOFT (como el AGENTS.md) no se suben: se excluyen de manera local con .git/info/exclude, sin tocar el .gitignore del proyecto.' },
    { tipo: 'resumen', items: [
      'Ante un mal resultado: ¿tenía la información para hacerlo bien?',
      'AGENTS.md: lo que aplica siempre, corto y específico.',
      'Si lo corregís dos veces, va al AGENTS.md.',
      'Global + repo + carpeta; el más cercano manda.',
      'Progressive disclosure: el detalle, solo cuando hace falta.'] },
    { tipo: 'challenge' },
    { tipo: 'cierre', siguiente: 'Módulo 3 · Especificar antes de construir' }
  ]
};
