// Contenido del pptx del Módulo 0. Las notas del orador repiten la narración del video.
module.exports = {
  titulo: 'Cómo piensa la IA',
  bajada: 'Por qué la IA acierta un día y al otro no, y qué hacer al respecto.',
  slides: [
    { tipo: 'portada', chip: '≈ 9 min · challenge al final',
      notas: 'Bienvenida al curso. En este módulo vemos cómo funciona un modelo de lenguaje por dentro, para entender por qué a veces acierta y a veces no. El ejemplo que nos acompaña en todo el curso es pagos-api, el proyecto de Juli.' },
    { tipo: 'objetivos', items: [
      ['Un LLM predice', 'Por qué la IA no consulta ni recuerda: predice.'],
      ['Tokens y ventana de contexto', 'Qué "sabe" el agente en cada momento y qué pasa cuando se llena.'],
      ['Probabilístico vs. determinístico', 'Qué le pedís al modelo y qué tiene que garantizar el código.'],
      ['Alucinaciones', 'Por qué inventa y cómo se controla de verdad.']],
      notas: 'Cuatro ideas que usamos todos los días aunque no las veamos. Al final hay un challenge y un quiz interactivo.' },
    { tipo: 'imagen', section: 'El problema', titulo: 'Misma pregunta, dos respuestas', img: 'problema',
      bullets: ['Juli le pide a la IA lo mismo dos días seguidos', 'El lunes, la respuesta funciona', 'El martes, usa una función que no existe en el repo', '¿Por qué pasa esto?'],
      clave: 'Para trabajar bien con IA, primero hay que entender cómo piensa.',
      notas: 'Juli trabaja en pagos-api. Le hace a la IA la misma pregunta dos días seguidos y recibe dos respuestas distintas; una hasta usa una función que no existe. Para trabajar bien con IA, primero hay que entender cómo piensa.' },
    { tipo: 'imagen', section: '0.1 · Un LLM predice', titulo: 'Un LLM predice, no consulta', img: 'predice',
      bullets: ['Genera texto pieza por pieza (token por token)', 'En cada paso elige el candidato más probable', 'No "busca" la respuesta: arma la que suena más probable'],
      clave: 'Lo que sale es lo más probable, no necesariamente lo correcto.',
      notas: 'Un LLM genera texto pieza por pieza. En cada paso elige, entre muchos candidatos, lo que es más probable que siga. No busca la respuesta: arma la que suena más probable.' },
    { tipo: 'imagen', section: '0.1 · Un LLM predice', titulo: 'Con qué trabaja el modelo', img: 'fuentes',
      bullets: ['Lo que aprendió en su entrenamiento', 'Lo que le das en el momento: tu pedido y el contexto', 'Tres consecuencias: puede variar, siempre suena seguro, solo sabe lo que ve'],
      clave: 'Casi todo lo que sigue en el curso existe para compensar estas tres consecuencias.',
      notas: 'No consulta una base de datos ni recuerda tu proyecto: trabaja con lo que aprendió y con lo que le das en el momento. De ahí salen tres consecuencias: puede variar, siempre suena seguro y solo sabe lo que ve.' },
    { tipo: 'imagen', section: '0.2 · Tokens', titulo: 'Tokens: la unidad de todo', img: 'tokens',
      bullets: ['El modelo lee tokens, no letras ni palabras', 'Un token ≈ un fragmento de palabra', 'Todo se mide en tokens: pedido, archivos, errores, historial', 'Más contexto: más caro y más lento'],
      clave: 'Costo, velocidad y límite de contexto se miden en tokens.',
      notas: 'El modelo no lee letras ni palabras: lee tokens, fragmentos de texto. Todo lo que procesa se mide en tokens, y por eso el costo y la velocidad dependen de ellos. Además hay un límite de cuántos puede considerar a la vez. La división que se muestra es ilustrativa: cada modelo tokeniza distinto.' },
    { tipo: 'imagen', section: '0.3 · Ventana de contexto', titulo: 'La ventana de contexto', img: 'ventana',
      bullets: ['Todo lo que el modelo tiene en cuenta a la vez', 'Instrucciones, AGENTS.md, archivos, comandos, conversación', 'Cuando se llena, compacta… y se pierden detalles', 'Ejemplo: la convención de logger.error se olvidó'],
      clave: 'Lo importante tiene que estar escrito donde siempre se carga (Módulo 2: AGENTS.md).',
      notas: 'La ventana de contexto es todo lo que el modelo puede tener en cuenta a la vez. Cuando se llena, el agente resume y compacta, y se pierden detalles. Por ejemplo, la convención de usar logger.error que Juli explicó al principio: una hora después el agente vuelve a usar console.log. No es que no quiera: ya no lo ve.' },
    { tipo: 'columnas', section: '0.4 · Prob. vs. determinístico', titulo: 'Probabilístico vs. determinístico',
      cols: [['Para el modelo (probabilístico)', 'F5A524', ['Entender una spec', 'Diseñar una solución', 'Escribir código', 'Explicar un error']],
             ['Para el código (determinístico)', '2FD7A4', ['Correr los tests', 'Validar el formato (linter)', 'Bloquear comandos riesgosos', 'Verificar que compile']]],
      clave: 'Regla de oro: si algo tiene que pasar siempre, no se lo pidas al modelo. Hacelo determinístico.',
      notas: 'El modelo razona y se adapta, pero puede variar o saltearse un paso. El código hace siempre lo mismo. No compiten, se complementan. Una instrucción en un prompt es una sugerencia; un test o un hook es una garantía. Lo aplicamos en el Módulo 4.' },
    { tipo: 'imagen', section: '0.5 · Alucinaciones', titulo: 'Alucinaciones: cómo se controlan', img: 'alucina',
      bullets: ['No funciona: escribir "no inventes" o confiar en el tono', 'Sí funciona: darle la fuente real (docs, código, MCP)', 'Que compile y corra tests', 'Pedirle de dónde sale cada dato', 'Revisión humana en los puntos críticos'], size: 14,
      clave: 'Las alucinaciones no se evitan pidiendo: se controlan con fuentes reales y verificación.',
      notas: 'Cuando el modelo no tiene el dato, completa con lo plausible: un método de otra versión de la librería, un endpoint que no existe. Y lo dice con el mismo tono seguro. Lo que funciona es darle la fuente real, que compile y corra tests, pedirle de dónde sale cada dato y revisión humana en los puntos críticos.' },
    { tipo: 'imagen', section: '0.6 · Ejemplo con Codex', titulo: 'Misma pregunta, distinto contexto', img: 'codex',
      bullets: ['Chat sin contexto: responde con un supuesto', 'Codex en el repo: busca, lee el archivo y cita la fuente', 'La respuesta de Codex se puede verificar'],
      clave: 'Misma pregunta. Distinto contexto. Distinto resultado.',
      notas: 'En pagos-api, la función calcularRecargo. En un chat sin contexto, la IA nunca vio el código y responde con un supuesto que suena perfecto. Codex trabaja dentro del repo: busca, lee el archivo y responde citando la fuente. La terminal del video es una simulación.' },
    { tipo: 'pasos', section: '0.6 · Ejemplo con Codex', titulo: 'Probalo vos', chip: '10 minutos · en tu proyecto',
      pasos: [['Que varíe', 'Pedile al chat lo mismo 3 veces y compará las respuestas.'],
              ['Que invente', 'Preguntale por una función que no existe en tu repo. ¿Qué te contesta?'],
              ['Que vea', 'Abrí Codex en tu repo, hacé la misma pregunta y pedile que cite archivo y línea.']],
      clave: 'En el Módulo 1 vemos por qué Codex puede leer tu repo: el agente y su harness.',
      notas: 'Tres pruebas cortas en el proyecto propio para ver con los propios ojos las tres consecuencias: varía, suena seguro y solo sabe lo que ve.' },
    { tipo: 'resumen', items: [
      'Un LLM predice lo más probable: no consulta ni recuerda.',
      'Todo se mide en tokens: más contexto, más caro y más lento.',
      'Solo sabe lo que entra en su ventana de contexto.',
      'Lo que tiene que pasar siempre, hacelo determinístico.',
      'Las alucinaciones se controlan con fuentes reales y verificación.'] },
    { tipo: 'challenge' },
    { tipo: 'cierre', siguiente: 'Módulo 1 · Del chat al agente' }
  ]
};
